# To create & activate environment {name} from this file, run:
#
#   (1) $ conda env create -f environment.yml
#   (2) $ conda activate {name}
#

name: clipboard-CMS
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.11
  - pip>=19.0
  - jupyter
  - pandas
  # - numpy

  # Dataviz
  - matplotlib
  - plotly
  - geopandas
  - geopy
  - seaborn

  # Stats
  - scipy
  - statsmodels
  - arviz

  # ETL
  # - requests
  # - pydantic
  # - bs4
  # - mysql

  # Ensures pycurl and wptools are installed correctly
  # - openssl
  # - pycurl

  # Secure API key retrieval
  - python-dotenv

  - pip:
    # Stats
    - bambi

    # Tables
    - great-tables
    - polars
    # - pyarrow
    # - tabulate

    # EDA
    - holidays

    # SQL
    # - mysql
    # - mysqlclient
    # - mysql-connector-python
    # - PyMySQL
    # - jsonschema

    # Typing / testing / linting
    # run `mypy --install-types` to install missing stubs. Pandas given below.
    - mypy
    - pandas-stubs
    - pytest
    - coverage
    - flake8
