# To create & activate environment {name} from this file, run:
#
#   (1) $ conda env create -f environment.yml
#   (2) $ conda activate {name}
#

name: clipboard-CMS
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.11
  - pip>=19.0
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - geopy
  # - mysql
  # - seaborn
  # - pydantic
  # - requests
  # - bs4

  # Ensures pycurl and wptools are installed correctly
  # - openssl
  # - pycurl

  # Secure API key retrieval
  # - python-dotenv

  - pip:
    # Tables
    - great-tables
    - polars
    # - pyarrow
    # - tabulate

    # SQL
    # - mysql
    # - mysqlclient
    # - mysql-connector-python
    # - PyMySQL
    # - jsonschema

    # Typing / testing / linting
    # run `mypy --install-types` to install missing stubs. Pandas given below.
    - mypy
    - pandas-stubs
    - pytest
    - coverage
    - flake8
